---
# Specify one of section openstackrc,token or password.
# Precedence order is :
# openstackrc > token > password
# Since tokens are epehemral It might often be suitable to use password style authetication.
openstackrc: ""
token:
    OS_TOKEN: ""
    OS_URL: ""
password:
    OS_AUTH_URL: ""
    OS_TENANT_ID: ""
    OS_TENANT_NAME: ""
    OS_USERNAME: ""
    OS_PASSWORD: ""
